### ISSUE TITLE
Placeable Parts

### ISSUE THREAD

**Issue by SilasContaifer** [Matamata-Animator/Matamata-Core#46]
Right now the code let us select poses with the _timestamps_ and it automatic select mouths - I would like to have the option to add new parts like **Eyes (with eyebrows)** we could have a similar characters.json for the eyes

And as @Yey007 had said

> At the start of the timestamp file we do something like this
> 
> eyes: eyes.json
> poses: characters.json
> ...
> 0000 name poses
> 0001 name eyes

This same logic could be applied to other parts like changing the character hands

**Comment by AI-Spawn** [comment]
Sounds awesome!

**Comment by SpeedyHorn** [comment]
+1

**Comment by AI-Spawn** [comment]
Ok I think I'll take a look at this on the side taking the approach we discussed on Discord a while ago. If all goes well this should be implemented with the 4.0 release which should be ready in the next month-ish (probably less but given that I want to add Mac support and test everything no promises on a timeline)

**Comment by AI-Spawn** [comment]
https://github.com/Matamata-Animator/Matamata-Core/tree/placeable_parts

**Comment by AI-Spawn** [comment]
Working from #51

**Comment by AI-Spawn** [comment]
Merged into main with 4.0
