### ISSUE TITLE
Mention that Vosk model is optional in readme

### ISSUE THREAD

**Issue by Venryx** [Matamata-Animator/Matamata-Core#58]
In the readme there is the install step:
> Install Vosk model through the [Vosk website](https://alphacephei.com/vosk/models) or using the automatic tool. This is a 1.8 GB file and thus will take some time, please have patience.

However, looking at the code, it appears that the Vosk model is only used if either:
1) The aligning-algorithm is set to "allosaurus". (which is not the default)
2) The aligning-algorithm is set to "gentle" (the default), and the user does not supply a script/manual-transcription file.

Given that downloading the model takes so long (something like 10 minutes), it seems worth mentioning in the readme something like:
> This step can be skipped if you're going to stick with the default aligner "gentle", and will always manually supply the script/text for the audio using the `text` argument.

**Comment by Venryx** [comment]
I'm proceeding further in the process now (having deleted the vosk model to confirm it's not necessary), and I'm seeing that the current code does actually still require the vosk model to have been downloaded, even though the code doesn't "use" the vosk model for my given options ("gentle" as transcriber, with a user-supplied script file).

I was able to fix this though by editing the `transcriber.ts` file: Removing the `var vosk = require("vosk");` line from the root module scope, and instead placing it as the first line within the `voskTranscribe` function. With that change, I am able to call `gentleAlign` (in `align.ts`) without any errors (despite not having the vosk model downloaded).

I will update this comment if I find other places in the code that depend on the vosk model having been downloaded, when they don't necessarily need to.

**Comment by AI-Spawn** [comment]
Thank you so much for your work! Vosk should also be skippable using `--transcriber watson --watson_api_key KEY`, I should add both of those flags to the default arguments table. Please submit a PR whenever you're ready, and again, thank you!
